In [44]:
import pandas as pd
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [78]:
movies_df = pd.read_csv('movies_features.csv')
watchlist_df = pd.read_csv('user_watchlist.csv')

In [76]:
movies_df.head()

,movie_id,title,overview,source_db,genre_action,genre_adventure,genre_animation,genre_comedy,genre_documentary,genre_drama,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_tv_movie,genre_war,popularity_norm,recency_score
0,39196,Aupa Etxebeste!,The same day that the Etxebeste Family are lea...,european_movies,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0.088407,1.453987e-18
1,54788,Eutsi!,"Two young lovers of cycling, in their thirties...",european_movies,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0.025484,2.809019e-17
2,80187,Gartxot,Gartxot is a Twelfth Century minstrel from the...,european_movies,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0.025484,1.407404e-14
3,80550,Bi anai,"At the death of his father, Paulo, the younges...",european_movies,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0.058371,2.780123e-13
4,97056,Stars to Wish Upon,Victoria is a republican widow who enters in t...,european_movies,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0.038843,4.371386e-14

In [47]:
watchlist_df iwant a movie recommendation modeli will recommending the movies to them based on the using thr

,id,movie_id,user_id,title,original_title,poster_path,movie_type,watched,source_db
0,12,655187,2.0,Coven,NaN,/lyB3yoQbGO3LiCVuSOD2g17Hr6p.jpg,Streamable,0,european_movies
1,13,80550,2.0,Bi anai,NaN,/sPUU8N0F0wCNapwMMeiWXONFpEz.jpg,Streamable,0,european_movies
2,15,477033,5.0,Errementari: The Blacksmith and the Devil,NaN,/ltpi1uLkvx2BKHWwbpMjqdAtdHn.jpg,Streamable,0,european_movies
3,16,762329,9.0,Ospel,NaN,/oHSOSIt4ZUGTfz8tvR9aPlAI7tt.jpg,Streamable,0,european_movies
4,19,744993,8.0,Nora,NaN,/rz9OvEmsHNPTeyGauqdD5Jhhm5m.jpg,Streamable,0,european_movies
...,...,...,...,...,...,...,...,...,...
85,171,1386368,390.0,Itoiz Summer Sessions,Itoiz udako sesioak,/eEONMjBZGNrOObTG9OiTZTfVSV.jpg,Streamable,0,european_movies
86,172,621410,1283.0,Above 592 Metres,592 metroz goiti,/6mcxcFQbKQJcKmUQ8q5OWhuRHZz.jpg,Streamable,0,european_movies
87,173,1440185,1303.0,"Jone, batzuetan","Jone, batzuetan",/o1jsDGlUrT6A1JGQGXz3XtgR81A.jpg,Streamable,0,european_movies
88,175,1467179,1271.0,A-Maniki,A-Maniki,/4htVRuirH5Qg1BXYq0uqBw6uGuq.jpg,Streamable,0,european_movies
89,176,1440185,1320.0,"Jone, batzuetan","Jone, batzuetan",/o1jsDGlUrT6A1JGQGXz3XtgR81A.jpg,Streamable,0,european_movies

In [48]:
movie

,movie_id,title,overview,source_db,genre_action,genre_adventure,genre_animation,genre_comedy,genre_documentary,genre_drama,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_tv_movie,genre_war,popularity_norm,recency_score
0,39196,Aupa Etxebeste!,The same day that the Etxebeste Family are lea...,european_movies,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0.088407,1.453987e-18

# clean and remove the duplicate movie data present

In [49]:
df = movies_df.drop_duplicates(subset='movie_id', keep='first')

In [50]:
df = df.drop_duplicates(subset='movie_id', keep='last')

In [51]:
df = df[~df.duplicated(subset='movie_id', keep=False)]

In [52]:
before = len(df)
df = df.drop_duplicates(subset='movie_id')
after = len(df)

print(f"Removed {before - after} duplicate rows")

Removed 0 duplicate rows

In [53]:
df.reset_index(drop=True, inplace=True)

In [54]:
df.shape

(333, 23)

In [55]:
movie = df[df['movie_id'] == 39196]

In [56]:
movie

,movie_id,title,overview,source_db,genre_action,genre_adventure,genre_animation,genre_comedy,genre_documentary,genre_drama,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_tv_movie,genre_war,popularity_norm,recency_score
0,39196,Aupa Etxebeste!,The same day that the Etxebeste Family are lea...,european_movies,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0.088407,1.453987e-18

In [57]:
df

,movie_id,title,overview,source_db,genre_action,genre_adventure,genre_animation,genre_comedy,genre_documentary,genre_drama,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_tv_movie,genre_war,popularity_norm,recency_score
0,39196,Aupa Etxebeste!,The same day that the Etxebeste Family are lea...,european_movies,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0.088407,1.453987e-18
1,54788,Eutsi!,"Two young lovers of cycling, in their thirties...",european_movies,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0.025484,2.809019e-17
2,80187,Gartxot,Gartxot is a Twelfth Century minstrel from the...,european_movies,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0.025484,1.407404e-14
3,80550,Bi anai,"At the death of his father, Paulo, the younges...",european_movies,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0.058371,2.780123e-13
4,97056,Stars to Wish Upon,Victoria is a republican widow who enters in t...,european_movies,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0.038843,4.371386e-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,1467179,A-Maniki,NaN,european_movies,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0.000868,2.110721e-01
329,1474737,Jo Ta Ke gola sartu arte,NaN,european_movies,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.003825,0.000000e+00
330,1476804,Mugarantz. Hacia la frontera,NaN,european_movies,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0.001068,1.598797e-01
331,1477810,Film Study 02: The Atrocity Exhibition,"In this second film study, some scenes from ""T...",european_movies,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0.001047,2.865048e-01
332,1479201,Ezkutuan,NaN,european_movies,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.008768,3.638145e-01

### join user watchhlist and movie data

In [58]:
joined_df = watchlist_df.merge(
    df,
    how="left",
    on="movie_id",
    suffixes=("_watch", "_movie")
)

# Drop rows where movie not found
joined_df = joined_df.dropna(subset=["popularity_norm"])

print("Joined shape:", joined_df.shape)
joined_df.head()

Joined shape: (87, 31)

,id,movie_id,user_id,title_watch,original_title,poster_path,movie_type,watched,source_db_watch,title_movie,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_tv_movie,genre_war,popularity_norm,recency_score
0,12,655187,2.0,Coven,NaN,/lyB3yoQbGO3LiCVuSOD2g17Hr6p.jpg,Streamable,0,european_movies,Coven,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.438630,2.547590e-05
1,13,80550,2.0,Bi anai,NaN,/sPUU8N0F0wCNapwMMeiWXONFpEz.jpg,Streamable,0,european_movies,Bi anai,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.058371,2.780123e-13
2,15,477033,5.0,Errementari: The Blacksmith and the Devil,NaN,/ltpi1uLkvx2BKHWwbpMjqdAtdHn.jpg,Streamable,0,european_movies,Errementari: The Blacksmith and the Devil,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.773835,1.336852e-07
3,16,762329,9.0,Ospel,NaN,/oHSOSIt4ZUGTfz8tvR9aPlAI7tt.jpg,Streamable,0,european_movies,Ospel,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.025484,1.726781e-05
4,19,744993,8.0,Nora,NaN,/rz9OvEmsHNPTeyGauqdD5Jhhm5m.jpg,Streamable,0,european_movies,Nora,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.109679,2.168502e-05

#### Make the float column like user_id and genre coulmn to int

In [64]:
# Identify genre columns dynamically
genre_cols = [c for c in joined_df.columns if c.startswith("genre_")]

# Columns that must be integer
int_cols = ["user_id"] + genre_cols

print(f"Total int columns: {len(int_cols)}")
int_cols[:10]  # preview

Total int columns: 18

['user_id',
 'genre_action',
 'genre_adventure',
 'genre_animation',
 'genre_comedy',
 'genre_documentary',
 'genre_drama',
 'genre_family',
 'genre_fantasy',
 'genre_history']

In [65]:
for col in int_cols:
    joined_df[col] = joined_df[col].fillna(0).astype(int)

In [66]:
joined_df[int_cols].dtypes

user_id                  int64
genre_action             int64
genre_adventure          int64
genre_animation          int64
genre_comedy             int64
genre_documentary        int64
genre_drama              int64
genre_family             int64
genre_fantasy            int64
genre_history            int64
genre_horror             int64
genre_music              int64
genre_mystery            int64
genre_romance            int64
genre_science_fiction    int64
genre_thriller           int64
genre_tv_movie           int64
genre_war                int64
dtype: object

In [67]:
joined_df[int_cols]

,user_id,genre_action,genre_adventure,genre_animation,genre_comedy,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_history,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_tv_movie,genre_war
0,2,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,5,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0
3,9,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,390,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
86,1283,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
87,1303,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
88,1271,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0
89,1320,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

### ⭐ CELL 4 — Convert Watchlist → Implicit Feedback

In [68]:
def compute_implicit_feedback(row):
    score = 1.0
    if row["watched"] == 1:
        score += 2.0
    return score

joined_df["implicit_score"] = joined_df.apply(
    compute_implicit_feedback, axis=1
)

joined_df[["user_id", "movie_id", "watched", "implicit_score"]].head()

   user_id  movie_id  watched  implicit_score
0        2    655187        0             1.0
1        2     80550        0             1.0
2        5    477033        0             1.0
3        9    762329        0             1.0
4        8    744993        0             1.0

### CELL 5 — Identify Genre Columns

In [69]:
genre_cols = [c for c in movies_df.columns if c.startswith("genre_")]
len(genre_cols), genre_cols[:10]

(17,
 ['genre_action',
  'genre_adventure',
  'genre_animation',
  'genre_comedy',
  'genre_documentary',
  'genre_drama',
  'genre_family',
  'genre_fantasy',
  'genre_history',
  'genre_horror'])

### CELL 6 — Build User Profiles

In [70]:
def build_user_profiles(joined_df, genre_cols):
    profiles = []

    for user_id, group in joined_df.groupby("user_id"):
        weights = group["implicit_score"].values.reshape(-1, 1)

        genre_matrix = group[genre_cols].values
        genre_pref = (genre_matrix * weights).sum(axis=0)
        genre_pref = genre_pref / (genre_pref.sum() + 1e-6)

        profile = {
            "user_id": user_id,
            "popularity_pref": np.average(
                group["popularity_norm"], weights=group["implicit_score"]
            ),
            "recency_pref": np.average(
                group["recency_score"], weights=group["implicit_score"]
            ),
        }

        for i, col in enumerate(genre_cols):
            profile[col] = genre_pref[i]

        profiles.append(profile)

    return pd.DataFrame(profiles)


profiles_df = build_user_profiles(joined_df, genre_cols)
profiles_df.head()

,user_id,popularity_pref,recency_pref,genre_action,genre_adventure,genre_animation,genre_comedy,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_history,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_thriller,genre_tv_movie,genre_war
0,2,0.248500,1.273795e-05,0.0,0.0,0.0,0.0,0.0,0.666666,0.0,0.000000,0.333333,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5,0.773835,1.336852e-07,0.0,0.0,0.0,0.0,0.0,0.333333,0.0,0.333333,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,8,0.084599,5.149698e-03,0.0,0.0,0.0,0.5,0.0,0.500000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9,0.025484,1.726781e-05,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.999999,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,11,0.822038,1.375568e-03,0.0,0.0,0.0,0.0,0.0,0.999999,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### CELL 7 — Hybrid Recommendation Function

In [72]:
import numpy as np

def recommend_for_user(
    user_profile,
    movies_df,
    genre_cols,
    watchlist_df,
    top_k=20,
):
    """
    Returns top_k movie recommendations for a user
    - Scores by genre, popularity, recency
    - Removes watched movies
    - Deduplicates same movie across multiple source_db
    """

    # ----------------------------
    # 1. GENRE SCORE
    # ----------------------------
    user_genres = user_profile[genre_cols].values.astype(float)
    movie_genres = movies_df[genre_cols].values.astype(float)

    genre_score = movie_genres @ user_genres

    # ----------------------------
    # 2. POPULARITY SCORE
    # ----------------------------
    popularity_score = 1 - np.abs(
        movies_df["popularity_norm"].values
        - user_profile["popularity_pref"]
    )

    # ----------------------------
    # 3. RECENCY SCORE
    # ----------------------------
    recency_score = 1 - np.abs(
        movies_df["recency_score"].values
        - user_profile["recency_pref"]
    )

    # ----------------------------
    # 4. FINAL WEIGHTED SCORE
    # ----------------------------
    final_score = (
        0.6 * genre_score
        + 0.25 * popularity_score
        + 0.15 * recency_score
    )

    # ----------------------------
    # 5. ATTACH SCORE
    # ----------------------------
    result = movies_df.copy()
    result["score"] = final_score

    # ----------------------------
    # 6. REMOVE WATCHED MOVIES
    # ----------------------------
    watched_movies = set(
        watchlist_df[
            watchlist_df["user_id"] == user_profile["user_id"]
        ]["movie_id"]
    )

    result = result[~result["movie_id"].isin(watched_movies)]

    # ----------------------------
    # 7. SORT BY SCORE
    # ----------------------------
    result = result.sort_values("score", ascending=False)

    # ----------------------------
    # 8. DEDUPLICATE SAME MOVIE
    #    (keep best-scoring version)
    # ----------------------------
    result = result.drop_duplicates(
        subset="title",
        keep="first"
    )

    # ----------------------------
    # 9. RETURN TOP-K
    # ----------------------------
    return result.head(top_k)[
        ["movie_id", "title", "score", "source_db"]
    ]

### 🎬 CELL 8 — Get Recommendations for a User

In [74]:
# Pick a user
user_profile = profiles_df.iloc[1]

recommendations = recommend_for_user(
    user_profile=user_profile,
    movies_df=movies_df,
    genre_cols=genre_cols,
    watchlist_df=watchlist_df,
    top_k=40,
)

recommendations

     movie_id                                title     score        source_db
168    776670                        All the Moons  0.862438  european_movies
142    726274                                Irati  0.705431  european_movies
297   1367125                                 Gaua  0.630749  european_movies
150    750461                              Dar-Dar  0.624672  european_movies
272   1275856                           Larramendi  0.613338  european_movies
127    660035               Euskal Harriaren ABDak  0.612912  european_movies
228   1018391                                 Mist  0.612709  european_movies
287   1305658                             Merkurio  0.608477  european_movies
308   1414723                             Gurutzea  0.607232  european_movies
229   1024287               Stillness in the Storm  0.587743  european_movies
20     260313                              Flowers  0.543459  european_movies
126    655187                                Coven  0.516195  european_movies
46     421560                            The Giant  0.510211  european_movies
255   1204156                          Betiko gaua  0.445243  european_movies
262   1247538                   The Last Romantics  0.443269  european_movies
72     529213                             The Deer  0.435716  european_movies
145    744993                                 Nora  0.433958  european_movies
21     263412                             Akelarre  0.431951  european_movies
54     438591                       Elf on the Run  0.430759  european_movies
9      150664                          For 80 Days  0.430610  european_movies
270   1274677                      Zergatik panpox  0.425324  european_movies
221    951719                               Thirst  0.424580  european_movies
143    736203                       Ane Is Missing  0.424086  european_movies
74     544914                               Dantza  0.423505  european_movies
144    736216                          Death Knell  0.422714  european_movies
33     351095                                Amama  0.422038  european_movies
227   1007722  The Disease Has Taken the Farmhouse  0.422006  european_movies
29     326176                        Under the Bed  0.421421  european_movies
147    749351                          Zeru horiek  0.421421  european_movies
215    916302                                Iñigo  0.421393  european_movies
55     448530                           Ehun metro  0.421144  european_movies
3       80550                              Bi anai  0.421134  european_movies
220    947643                      Sultana's Dream  0.420959  european_movies
63     473028                               Hileta  0.420932  european_movies
246   1172099                           Bizkarsoro  0.419836  european_movies
10     158009         The Legend of the North Wind  0.419815  european_movies
84     553094                    Gure oroitzapenak  0.419411  european_movies
208    874066                                Kinka  0.418779  european_movies
15     189330                        Ander eta Yul  0.418762  european_movies
44     416586                           Kalebegiak  0.417241  european_movies

### CELL 9 — (Optional) Filter Already Watched Movies

In [79]:
watched_movies = set(
    watchlist_df[
        watchlist_df["user_id"] == user_profile["user_id"]
    ]["movie_id"]
)

filtered_recs = recommendations[
    ~recommendations["movie_id"].isin(watched_movies)
]

filtered_recs[["title", "score", "source_db"]]

                                   title     score        source_db
168                        All the Moons  0.862438  european_movies
142                                Irati  0.705431  european_movies
297                                 Gaua  0.630749  european_movies
150                              Dar-Dar  0.624672  european_movies
272                           Larramendi  0.613338  european_movies
127               Euskal Harriaren ABDak  0.612912  european_movies
228                                 Mist  0.612709  european_movies
287                             Merkurio  0.608477  european_movies
308                             Gurutzea  0.607232  european_movies
229               Stillness in the Storm  0.587743  european_movies
20                               Flowers  0.543459  european_movies
126                                Coven  0.516195  european_movies
46                             The Giant  0.510211  european_movies
255                          Betiko gaua  0.445243  european_movies
262                   The Last Romantics  0.443269  european_movies
72                              The Deer  0.435716  european_movies
145                                 Nora  0.433958  european_movies
21                              Akelarre  0.431951  european_movies
54                        Elf on the Run  0.430759  european_movies
9                            For 80 Days  0.430610  european_movies
270                      Zergatik panpox  0.425324  european_movies
221                               Thirst  0.424580  european_movies
143                       Ane Is Missing  0.424086  european_movies
74                                Dantza  0.423505  european_movies
144                          Death Knell  0.422714  european_movies
33                                 Amama  0.422038  european_movies
227  The Disease Has Taken the Farmhouse  0.422006  european_movies
29                         Under the Bed  0.421421  european_movies
147                          Zeru horiek  0.421421  european_movies
215                                Iñigo  0.421393  european_movies
55                            Ehun metro  0.421144  european_movies
3                                Bi anai  0.421134  european_movies
220                      Sultana's Dream  0.420959  european_movies
63                                Hileta  0.420932  european_movies
246                           Bizkarsoro  0.419836  european_movies
10          The Legend of the North Wind  0.419815  european_movies
84                     Gure oroitzapenak  0.419411  european_movies
208                                Kinka  0.418779  european_movies
15                         Ander eta Yul  0.418762  european_movies
44                            Kalebegiak  0.417241  european_movies

# Save the final user interaction + cleaned Movie dataset

In [105]:
output_path = "final_user_movie_dataset.csv"
joined_df.to_csv(output_path, index=False)

print(f"Saved dataset → {output_path}")

Saved dataset → final_user_movie_dataset.csv